language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

branches:
  only:
  - master

services:
    - redis-server
    - mysql

cache:
    directories:
      - "$HOME/.composer/cache"

before_install:
  - sudo apt-get -y update
  - sudo apt-get -y install libmemcached-dev
  - pecl channel-update pecl.php.net
  - travis_retry composer self-update
  - composer install
  - mysql -e "CREATE USER 'ragnarok'@'localhost' IDENTIFIED BY 'ragnarok';"
  - mysql -e "CREATE DATABASE ragnarok;"
  - mysql -e "GRANT ALL PRIVILEGES ON ragnarok.* TO 'ragnarok'@'localhost';"
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf 2>/dev/null || true
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - git clone --depth 1 https://github.com/HerculesWS/Hercules.git tmp
  - mysql -uragnarok -pragnarok ragnarok < tmp/sql-files/main.sql
  - mysql -uragnarok -pragnarok ragnarok < tmp/sql-files/logs.sql
  - rm -rf tmp

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - vendor/bin/codacycoverage clover coverage.xml
